// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Spv.WinForms.Models;

public partial class VGroupmember
{
    public int? Userid { get; set; }

    public int? Groupid { get; set; }

    public string? Personalnr { get; set; }

    public string? Nachname { get; set; }

    public string? Vorname { get; set; }

    public int? Gesperrt { get; set; }
}