// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Spv.WinForms.Models;

public partial class VMeassureHn248konz
{
    public Guid OrderId { get; set; }

    public string OrderNb { get; set; } = null!;

    public string? MatNb { get; set; }

    public Guid Serialid { get; set; }

    public string? Serialnb { get; set; }

    public string? ValveType { get; set; }

    public double? P1 { get; set; }

    public double? P2 { get; set; }

    public string? Drawing { get; set; }

    public int? Type { get; set; }

    public double? ValueInner { get; set; }

    public Guid? TestId { get; set; }

    public int State { get; set; }

    public double? ValueOuter { get; set; }

    public int? OrderType { get; set; }

    public int? OrderStateId { get; set; }
}