// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Spv.WinForms.Models;

public partial class VSelftest
{
    public DateTime? SelfTestDate { get; set; }

    public DateTime? Meassuredate { get; set; }

    public int? NozzleNb { get; set; }

    public double? DebitValue { get; set; }

    public double? FlowValue { get; set; }

    public int? ValveOk { get; set; }

    public string? TestedBy { get; set; }

    public string? FirstName { get; set; }

    public string? Q5 { get; set; }

    public double? Q5calc { get; set; }

    public string? Q5inner { get; set; }

    public double? Q5innerCalc { get; set; }

    public string? Q5outer { get; set; }

    public double? Q5outerCalc { get; set; }

    public string? Pressure { get; set; }

    public double? PressureCalc { get; set; }

    public string? PressureP1 { get; set; }

    public double? P1calc { get; set; }

    public string? PressureP2 { get; set; }

    public double? P2calc { get; set; }

    public string? Volume { get; set; }

    public double? VolumeCalc { get; set; }

    public string? Time { get; set; }

    public double? TimeCalc { get; set; }

    public string? DebitValueUnit { get; set; }

    public string? FlowValueUnit { get; set; }

    public Guid Id { get; set; }
}