// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Spv.WinForms.Models;
using System;
using System.Collections.Generic;

#nullable disable

namespace Spv.WinForms.Models.Configurations
{
    public partial class AuftragsstatiConfiguration : IEntityTypeConfiguration<Auftragsstati>
    {
        public void Configure(EntityTypeBuilder<Auftragsstati> entity)
        {
            entity.HasKey(e => e.Auftragsstatusid);

            entity.ToTable("auftragsstati");

            entity.Property(e => e.Auftragsstatusid)
                .ValueGeneratedNever()
                .HasColumnName("auftragsstatusid");
            entity.Property(e => e.Auftragsstatus)
                .HasMaxLength(50)
                .HasColumnName("auftragsstatus");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Auftragsstati> entity);
    }
}
