// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Spv.WinForms.Models;
using System;
using System.Collections.Generic;

#nullable disable

namespace Spv.WinForms.Models.Configurations
{
    public partial class ColumnheaderConfiguration : IEntityTypeConfiguration<Columnheader>
    {
        public void Configure(EntityTypeBuilder<Columnheader> entity)
        {
            entity.HasKey(e => new { e.Fieldname, e.Lang }).HasName("PK_spaltenueberschriften");

            entity.ToTable("columnheader");

            entity.Property(e => e.Fieldname)
                .HasMaxLength(255)
                .HasColumnName("fieldname");
            entity.Property(e => e.Lang)
                .HasMaxLength(5)
                .HasColumnName("lang");
            entity.Property(e => e.Displayname)
                .HasMaxLength(255)
                .HasColumnName("displayname");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Columnheader> entity);
    }
}
