// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Spv.WinForms.Models;
using System;
using System.Collections.Generic;

#nullable disable

namespace Spv.WinForms.Models.Configurations
{
    public partial class DbversionConfiguration : IEntityTypeConfiguration<Dbversion>
    {
        public void Configure(EntityTypeBuilder<Dbversion> entity)
        {
            entity
                .HasNoKey()
                .ToTable("dbversion");

            entity.Property(e => e.Dbdate)
                .HasColumnType("datetime")
                .HasColumnName("dbdate");
            entity.Property(e => e.Dbversion1)
                .HasMaxLength(10)
                .HasColumnName("dbversion");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Dbversion> entity);
    }
}
