// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Spv.WinForms.Models;
using System;
using System.Collections.Generic;

#nullable disable

namespace Spv.WinForms.Models.Configurations
{
    public partial class DefaultSettingConfiguration : IEntityTypeConfiguration<DefaultSetting>
    {
        public void Configure(EntityTypeBuilder<DefaultSetting> entity)
        {
            entity
                .HasNoKey()
                .ToTable("default_settings");

            entity.Property(e => e.Created).HasColumnType("datetime");
            entity.Property(e => e.LastEdit).HasColumnType("datetime");
            entity.Property(e => e.Pressure).HasMaxLength(20);
            entity.Property(e => e.PressureP1).HasMaxLength(20);
            entity.Property(e => e.PressureP2).HasMaxLength(20);
            entity.Property(e => e.Q5).HasMaxLength(20);
            entity.Property(e => e.Q5inner).HasMaxLength(20);
            entity.Property(e => e.Q5outer).HasMaxLength(20);
            entity.Property(e => e.Time).HasMaxLength(20);
            entity.Property(e => e.Volume).HasMaxLength(20);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<DefaultSetting> entity);
    }
}
