// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Spv.WinForms.Models;
using System;
using System.Collections.Generic;

#nullable disable

namespace Spv.WinForms.Models.Configurations
{
    public partial class GroupsModuleConfiguration : IEntityTypeConfiguration<GroupsModule>
    {
        public void Configure(EntityTypeBuilder<GroupsModule> entity)
        {
            entity
                .HasNoKey()
                .ToTable("groups_modules");

            entity.Property(e => e.Access).HasColumnName("access");
            entity.Property(e => e.Groupid).HasColumnName("groupid");
            entity.Property(e => e.Modulid).HasColumnName("modulid");
            entity.Property(e => e.Readonly).HasColumnName("readonly");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<GroupsModule> entity);
    }
}
