// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Spv.WinForms.Models;
using System;
using System.Collections.Generic;

#nullable disable

namespace Spv.WinForms.Models.Configurations
{
    public partial class Hn248konzConfiguration : IEntityTypeConfiguration<Hn248konz>
    {
        public void Configure(EntityTypeBuilder<Hn248konz> entity)
        {
            entity
                .HasNoKey()
                .ToTable("hn248konz");

            entity.Property(e => e.Aussenrate).HasColumnName("aussenrate");
            entity.Property(e => e.Aussenzeit)
                .HasMaxLength(255)
                .HasColumnName("aussenzeit");
            entity.Property(e => e.Beipruefdruck).HasColumnName("beipruefdruck");
            entity.Property(e => e.Bemerkungen)
                .HasMaxLength(255)
                .HasColumnName("bemerkungen");
            entity.Property(e => e.Innenrate).HasColumnName("innenrate");
            entity.Property(e => e.Innenzeit)
                .HasMaxLength(255)
                .HasColumnName("innenzeit");
            entity.Property(e => e.ModifiedBy)
                .HasMaxLength(255)
                .HasColumnName("modifiedBy");
            entity.Property(e => e.Ventiltype)
                .HasMaxLength(255)
                .HasColumnName("ventiltype");
            entity.Property(e => e.Zeichnung)
                .HasMaxLength(255)
                .HasColumnName("zeichnung");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Hn248konz> entity);
    }
}
