// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Spv.WinForms.Models;
using System;
using System.Collections.Generic;

#nullable disable

namespace Spv.WinForms.Models.Configurations
{
    public partial class MeassureConfiguration : IEntityTypeConfiguration<Meassure>
    {
        public void Configure(EntityTypeBuilder<Meassure> entity)
        {
            entity
                .HasNoKey()
                .ToTable("meassure");

            entity.Property(e => e.Created)
                .HasColumnType("datetime")
                .HasColumnName("created");
            entity.Property(e => e.CreatedBy).HasColumnName("created_by");
            entity.Property(e => e.DateInner).HasColumnType("datetime");
            entity.Property(e => e.DateOuter).HasColumnType("datetime");
            entity.Property(e => e.Deleted)
                .HasColumnType("datetime")
                .HasColumnName("deleted");
            entity.Property(e => e.DeletedBy).HasColumnName("deleted_by");
            entity.Property(e => e.Innerrate).HasColumnName("innerrate");
            entity.Property(e => e.Innertime).HasColumnName("innertime");
            entity.Property(e => e.Isdeleted)
                .HasDefaultValue(0)
                .HasColumnName("isdeleted");
            entity.Property(e => e.Issend2esm)
                .HasDefaultValue(0)
                .HasColumnName("issend2esm");
            entity.Property(e => e.Outerrate).HasColumnName("outerrate");
            entity.Property(e => e.Outertime).HasColumnName("outertime");
            entity.Property(e => e.Pressure).HasColumnName("pressure");
            entity.Property(e => e.Send2esm)
                .HasColumnType("datetime")
                .HasColumnName("send2esm");
            entity.Property(e => e.Send2esmBy).HasColumnName("send2esm_by");
            entity.Property(e => e.SerialId).HasColumnName("SerialID");
            entity.Property(e => e.TestId).HasColumnName("TestID");
            entity.Property(e => e.Vessel).HasColumnName("vessel");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Meassure> entity);
    }
}
