// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Spv.WinForms.Models;
using System;
using System.Collections.Generic;

#nullable disable

namespace Spv.WinForms.Models.Configurations
{
    public partial class OrderConfiguration : IEntityTypeConfiguration<Order>
    {
        public void Configure(EntityTypeBuilder<Order> entity)
        {
            entity.ToTable("orders");

            entity.HasIndex(e => e.OrderDate, "NonClusteredIndex-20240411-180933").IsDescending();

            entity.Property(e => e.OrderId)
                .HasDefaultValueSql("(newid())")
                .HasColumnName("OrderID");
            entity.Property(e => e.Closed)
                .HasColumnType("datetime")
                .HasColumnName("closed");
            entity.Property(e => e.ClosedBy).HasColumnName("closed_by");
            entity.Property(e => e.Created)
                .HasColumnType("datetime")
                .HasColumnName("created");
            entity.Property(e => e.CreatedBy).HasColumnName("created_by");
            entity.Property(e => e.Deleted)
                .HasColumnType("datetime")
                .HasColumnName("deleted");
            entity.Property(e => e.DeletedBy).HasColumnName("deleted_by");
            entity.Property(e => e.Isdeleted)
                .HasDefaultValue(0)
                .HasColumnName("isdeleted");
            entity.Property(e => e.Opened)
                .HasColumnType("datetime")
                .HasColumnName("opened");
            entity.Property(e => e.OpenedBy).HasColumnName("opened_by");
            entity.Property(e => e.OrderDate).HasColumnType("datetime");
            entity.Property(e => e.OrderNb).HasMaxLength(20);
            entity.Property(e => e.OrderStateId).HasColumnName("OrderStateID");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Order> entity);
    }
}
