// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Spv.WinForms.Models;
using System;
using System.Collections.Generic;

#nullable disable

namespace Spv.WinForms.Models.Configurations
{
    public partial class OrdersDetailConfiguration : IEntityTypeConfiguration<OrdersDetail>
    {
        public void Configure(EntityTypeBuilder<OrdersDetail> entity)
        {
            entity.HasKey(e => e.Serialid);

            entity.ToTable("orders_details");

            entity.Property(e => e.Serialid)
                .ValueGeneratedNever()
                .HasColumnName("serialid");
            entity.Property(e => e.Created)
                .HasColumnType("datetime")
                .HasColumnName("created");
            entity.Property(e => e.CreatedBy).HasColumnName("created_by");
            entity.Property(e => e.Deleted)
                .HasColumnType("datetime")
                .HasColumnName("deleted");
            entity.Property(e => e.DeletedBy).HasColumnName("deleted_by");
            entity.Property(e => e.Drawing).HasMaxLength(50);
            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.Isdeleted)
                .HasDefaultValue(0)
                .HasColumnName("isdeleted");
            entity.Property(e => e.MatDesc).HasMaxLength(255);
            entity.Property(e => e.MatNb).HasMaxLength(20);
            entity.Property(e => e.Orderid).HasColumnName("orderid");
            entity.Property(e => e.Serialnb)
                .HasMaxLength(20)
                .HasColumnName("serialnb");
            entity.Property(e => e.Type).HasColumnName("type");
            entity.Property(e => e.ValveType).HasMaxLength(20);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<OrdersDetail> entity);
    }
}
