// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Spv.WinForms.Models;
using System;
using System.Collections.Generic;

#nullable disable

namespace Spv.WinForms.Models.Configurations
{
    public partial class PruefLockConfiguration : IEntityTypeConfiguration<PruefLock>
    {
        public void Configure(EntityTypeBuilder<PruefLock> entity)
        {
            entity
                .HasNoKey()
                .ToTable("pruef_locks");

            entity.Property(e => e.Auftragstypeid).HasColumnName("auftragstypeid");
            entity.Property(e => e.Datum)
                .HasColumnType("datetime")
                .HasColumnName("datum");
            entity.Property(e => e.Fertnr)
                .HasMaxLength(50)
                .HasColumnName("fertnr");
            entity.Property(e => e.Prid).HasColumnName("prid");
            entity.Property(e => e.Srnr)
                .HasMaxLength(20)
                .HasColumnName("srnr");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<PruefLock> entity);
    }
}
