// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Spv.WinForms.Models;
using System;
using System.Collections.Generic;

#nullable disable

namespace Spv.WinForms.Models.Configurations
{
    public partial class PruefauftraegeStatiConfiguration : IEntityTypeConfiguration<PruefauftraegeStati>
    {
        public void Configure(EntityTypeBuilder<PruefauftraegeStati> entity)
        {
            entity
                .HasNoKey()
                .ToTable("pruefauftraege_stati");

            entity.Property(e => e.Datum)
                .HasColumnType("datetime")
                .HasColumnName("datum");
            entity.Property(e => e.Deleted)
                .HasDefaultValue(0)
                .HasColumnName("deleted");
            entity.Property(e => e.DeletedAm)
                .HasColumnType("datetime")
                .HasColumnName("deleted_am");
            entity.Property(e => e.DeletedVon).HasColumnName("deleted_von");
            entity.Property(e => e.Pruefauftragid).HasColumnName("pruefauftragid");
            entity.Property(e => e.Pruefstatusid).HasColumnName("pruefstatusid");
            entity.Property(e => e.Userid).HasColumnName("userid");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<PruefauftraegeStati> entity);
    }
}
