// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Spv.WinForms.Models;
using System;
using System.Collections.Generic;

#nullable disable

namespace Spv.WinForms.Models.Configurations
{
    public partial class PruefauftraegeConfiguration : IEntityTypeConfiguration<Pruefauftraege>
    {
        public void Configure(EntityTypeBuilder<Pruefauftraege> entity)
        {
            entity.HasKey(e => e.Pruefauftragid);

            entity.ToTable("pruefauftraege");

            entity.Property(e => e.Pruefauftragid)
                .ValueGeneratedNever()
                .HasColumnName("pruefauftragid");
            entity.Property(e => e.Abnahmeges)
                .HasMaxLength(50)
                .HasColumnName("abnahmeges");
            entity.Property(e => e.Abnahmenummer)
                .HasMaxLength(50)
                .HasColumnName("abnahmenummer");
            entity.Property(e => e.Auftragstypeid).HasColumnName("auftragstypeid");
            entity.Property(e => e.DatumAm)
                .HasColumnType("datetime")
                .HasColumnName("datum_am");
            entity.Property(e => e.Deleted)
                .HasDefaultValue(0)
                .HasColumnName("deleted");
            entity.Property(e => e.DeletedAm)
                .HasColumnType("datetime")
                .HasColumnName("deleted_am");
            entity.Property(e => e.DeletedVon).HasColumnName("deleted_von");
            entity.Property(e => e.Exportiert).HasColumnName("exportiert");
            entity.Property(e => e.ExportiertAm)
                .HasColumnType("datetime")
                .HasColumnName("exportiert_am");
            entity.Property(e => e.Fertnr)
                .HasMaxLength(12)
                .HasColumnName("fertnr");
            entity.Property(e => e.Pdruck).HasColumnName("pdruck");
            entity.Property(e => e.Pmax).HasColumnName("pmax");
            entity.Property(e => e.Pmin).HasColumnName("pmin");
            entity.Property(e => e.Popen).HasColumnName("popen");
            entity.Property(e => e.Prid).HasColumnName("prid");
            entity.Property(e => e.Pruefstatusid).HasColumnName("pruefstatusid");
            entity.Property(e => e.Srnr)
                .HasMaxLength(20)
                .HasColumnName("srnr");
            entity.Property(e => e.Userid).HasColumnName("userid");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Pruefauftraege> entity);
    }
}
