// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Spv.WinForms.Models;
using System;
using System.Collections.Generic;

#nullable disable

namespace Spv.WinForms.Models.Configurations
{
    public partial class SettingConfiguration : IEntityTypeConfiguration<Setting>
    {
        public void Configure(EntityTypeBuilder<Setting> entity)
        {
            entity.HasKey(e => e.Id).HasName("PK_einstellungen");

            entity.ToTable("settings");

            entity.Property(e => e.Id)
                .ValueGeneratedNever()
                .HasColumnName("id");
            entity.Property(e => e.Charsonder)
                .HasMaxLength(5)
                .HasColumnName("charsonder");
            entity.Property(e => e.Charstandard)
                .HasMaxLength(5)
                .HasColumnName("charstandard");
            entity.Property(e => e.Charstorno)
                .HasMaxLength(5)
                .HasColumnName("charstorno");
            entity.Property(e => e.Exportdetail)
                .HasMaxLength(255)
                .HasColumnName("exportdetail");
            entity.Property(e => e.Exportmaster)
                .HasMaxLength(255)
                .HasColumnName("exportmaster");
            entity.Property(e => e.Importdetail)
                .HasMaxLength(255)
                .HasColumnName("importdetail");
            entity.Property(e => e.Importmaster)
                .HasMaxLength(255)
                .HasColumnName("importmaster");
            entity.Property(e => e.Sapclosedpath)
                .HasMaxLength(255)
                .HasColumnName("sapclosedpath");
            entity.Property(e => e.Sapexportpath)
                .HasMaxLength(255)
                .HasColumnName("sapexportpath");
            entity.Property(e => e.Sapimportoldpath)
                .HasMaxLength(255)
                .HasColumnName("sapimportoldpath");
            entity.Property(e => e.Sapimportpath)
                .HasMaxLength(255)
                .HasColumnName("sapimportpath");
            entity.Property(e => e.Sapprotokollpath)
                .HasMaxLength(255)
                .HasColumnName("sapprotokollpath");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Setting> entity);
    }
}
