// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Spv.WinForms.Models;
using System;
using System.Collections.Generic;

#nullable disable

namespace Spv.WinForms.Models.Configurations
{
    public partial class TesttypenConfiguration : IEntityTypeConfiguration<Testtypen>
    {
        public void Configure(EntityTypeBuilder<Testtypen> entity)
        {
            entity.HasKey(e => e.Prueftypid).HasName("PK_prueftypen");

            entity.ToTable("testtypen");

            entity.Property(e => e.Prueftypid)
                .ValueGeneratedNever()
                .HasColumnName("prueftypid");
            entity.Property(e => e.Prueftyp)
                .HasMaxLength(50)
                .HasColumnName("prueftyp");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Testtypen> entity);
    }
}
