// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Spv.WinForms.Models;
using System;
using System.Collections.Generic;

#nullable disable

namespace Spv.WinForms.Models.Configurations
{
    public partial class VColumnheaderConfiguration : IEntityTypeConfiguration<VColumnheader>
    {
        public void Configure(EntityTypeBuilder<VColumnheader> entity)
        {
            entity
                .HasNoKey()
                .ToView("v_columnheader");

            entity.Property(e => e.Displayname)
                .HasMaxLength(255)
                .HasColumnName("displayname");
            entity.Property(e => e.Fieldname)
                .HasMaxLength(255)
                .HasColumnName("fieldname");
            entity.Property(e => e.Lang)
                .HasMaxLength(5)
                .HasColumnName("lang");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<VColumnheader> entity);
    }
}
