// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Spv.WinForms.Models;
using System;
using System.Collections.Generic;

#nullable disable

namespace Spv.WinForms.Models.Configurations
{
    public partial class VGroupmemberConfiguration : IEntityTypeConfiguration<VGroupmember>
    {
        public void Configure(EntityTypeBuilder<VGroupmember> entity)
        {
            entity
                .HasNoKey()
                .ToView("v_groupmembers");

            entity.Property(e => e.Gesperrt).HasColumnName("gesperrt");
            entity.Property(e => e.Groupid).HasColumnName("groupid");
            entity.Property(e => e.Nachname)
                .HasMaxLength(50)
                .HasColumnName("nachname");
            entity.Property(e => e.Personalnr)
                .HasMaxLength(50)
                .HasColumnName("personalnr");
            entity.Property(e => e.Userid).HasColumnName("userid");
            entity.Property(e => e.Vorname)
                .HasMaxLength(50)
                .HasColumnName("vorname");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<VGroupmember> entity);
    }
}
