// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Spv.WinForms.Models;
using System;
using System.Collections.Generic;

#nullable disable

namespace Spv.WinForms.Models.Configurations
{
    public partial class VMeassuredValConfiguration : IEntityTypeConfiguration<VMeassuredVal>
    {
        public void Configure(EntityTypeBuilder<VMeassuredVal> entity)
        {
            entity
                .HasNoKey()
                .ToView("v_meassured_val");

            entity.Property(e => e.Drawing).HasMaxLength(50);
            entity.Property(e => e.Esmid).HasColumnName("ESMID");
            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.MatDesc).HasMaxLength(255);
            entity.Property(e => e.MatNb).HasMaxLength(20);
            entity.Property(e => e.Mdate)
                .HasColumnType("datetime")
                .HasColumnName("mdate");
            entity.Property(e => e.MeassureDate).HasColumnType("datetime");
            entity.Property(e => e.MeassuredUnit).HasMaxLength(20);
            entity.Property(e => e.Mtime).HasColumnName("MTime");
            entity.Property(e => e.Orderid).HasColumnName("orderid");
            entity.Property(e => e.Q5).HasMaxLength(20);
            entity.Property(e => e.Q5calc).HasColumnName("Q5Calc");
            entity.Property(e => e.SerialId).HasColumnName("SerialID");
            entity.Property(e => e.Serialnb)
                .HasMaxLength(20)
                .HasColumnName("serialnb");
            entity.Property(e => e.TestId).HasColumnName("TestID");
            entity.Property(e => e.Time).HasMaxLength(20);
            entity.Property(e => e.Type).HasColumnName("type");
            entity.Property(e => e.ValveType).HasMaxLength(20);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<VMeassuredVal> entity);
    }
}
