// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Spv.WinForms.Models;
using System;
using System.Collections.Generic;

#nullable disable

namespace Spv.WinForms.Models.Configurations
{
    public partial class VMeassureConfiguration : IEntityTypeConfiguration<VMeassure>
    {
        public void Configure(EntityTypeBuilder<VMeassure> entity)
        {
            entity
                .HasNoKey()
                .ToView("v_meassure");

            entity.Property(e => e.Innerrate).HasColumnName("innerrate");
            entity.Property(e => e.Innertime).HasColumnName("innertime");
            entity.Property(e => e.Issend2esm).HasColumnName("issend2esm");
            entity.Property(e => e.Outerrate).HasColumnName("outerrate");
            entity.Property(e => e.Outertime).HasColumnName("outertime");
            entity.Property(e => e.P1calc).HasColumnName("P1Calc");
            entity.Property(e => e.P2calc).HasColumnName("P2Calc");
            entity.Property(e => e.Pressure).HasColumnName("pressure");
            entity.Property(e => e.PressureP1).HasMaxLength(20);
            entity.Property(e => e.PressureP2).HasMaxLength(20);
            entity.Property(e => e.PressureUnit).HasMaxLength(20);
            entity.Property(e => e.Q5).HasMaxLength(20);
            entity.Property(e => e.Q5calc).HasColumnName("Q5Calc");
            entity.Property(e => e.Q5inner).HasMaxLength(20);
            entity.Property(e => e.Q5innerCalc).HasColumnName("Q5InnerCalc");
            entity.Property(e => e.Q5outer).HasMaxLength(20);
            entity.Property(e => e.Q5outerCalc).HasColumnName("Q5OuterCalc");
            entity.Property(e => e.SerialId).HasColumnName("SerialID");
            entity.Property(e => e.TestId).HasColumnName("TestID");
            entity.Property(e => e.Testtype).HasColumnName("testtype");
            entity.Property(e => e.Time).HasMaxLength(20);
            entity.Property(e => e.TimeUnit).HasMaxLength(20);
            entity.Property(e => e.Vessel).HasColumnName("vessel");
            entity.Property(e => e.Volume).HasMaxLength(20);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<VMeassure> entity);
    }
}
