// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Spv.WinForms.Models;
using System;
using System.Collections.Generic;

#nullable disable

namespace Spv.WinForms.Models.Configurations
{
    public partial class VMemberofConfiguration : IEntityTypeConfiguration<VMemberof>
    {
        public void Configure(EntityTypeBuilder<VMemberof> entity)
        {
            entity
                .HasNoKey()
                .ToView("v_memberof");

            entity.Property(e => e.Groupid).HasColumnName("groupid");
            entity.Property(e => e.Ngroup)
                .HasMaxLength(50)
                .HasColumnName("ngroup");
            entity.Property(e => e.Userid).HasColumnName("userid");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<VMemberof> entity);
    }
}
