// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Spv.WinForms.Models;
using System;
using System.Collections.Generic;

#nullable disable

namespace Spv.WinForms.Models.Configurations
{
    public partial class VMemberrightConfiguration : IEntityTypeConfiguration<VMemberright>
    {
        public void Configure(EntityTypeBuilder<VMemberright> entity)
        {
            entity
                .HasNoKey()
                .ToView("v_memberrights");

            entity.Property(e => e.Access).HasColumnName("access");
            entity.Property(e => e.Groupid).HasColumnName("groupid");
            entity.Property(e => e.Modulid).HasColumnName("modulid");
            entity.Property(e => e.Readonly).HasColumnName("readonly");
            entity.Property(e => e.Userid).HasColumnName("userid");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<VMemberright> entity);
    }
}
