// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Spv.WinForms.Models;
using System;
using System.Collections.Generic;

#nullable disable

namespace Spv.WinForms.Models.Configurations
{
    public partial class VTestsPerTestidConfiguration : IEntityTypeConfiguration<VTestsPerTestid>
    {
        public void Configure(EntityTypeBuilder<VTestsPerTestid> entity)
        {
            entity
                .HasNoKey()
                .ToView("v_tests_per_testid");

            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.Mdate)
                .HasColumnType("smalldatetime")
                .HasColumnName("mdate");
            entity.Property(e => e.TestId).HasColumnName("TestID");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<VTestsPerTestid> entity);
    }
}
