// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Spv.WinForms.Models;
using System;
using System.Collections.Generic;

#nullable disable

namespace Spv.WinForms.Models.Configurations
{
    public partial class VUnitcalcConfiguration : IEntityTypeConfiguration<VUnitcalc>
    {
        public void Configure(EntityTypeBuilder<VUnitcalc> entity)
        {
            entity
                .HasNoKey()
                .ToView("v_unitcalc");

            entity.Property(e => e.P1calc).HasColumnName("P1Calc");
            entity.Property(e => e.P2calc).HasColumnName("P2Calc");
            entity.Property(e => e.Pressure).HasMaxLength(20);
            entity.Property(e => e.PressureP1).HasMaxLength(20);
            entity.Property(e => e.PressureP2).HasMaxLength(20);
            entity.Property(e => e.Q5).HasMaxLength(20);
            entity.Property(e => e.Q5calc).HasColumnName("Q5Calc");
            entity.Property(e => e.Q5inner).HasMaxLength(20);
            entity.Property(e => e.Q5innerCalc).HasColumnName("Q5InnerCalc");
            entity.Property(e => e.Q5outer).HasMaxLength(20);
            entity.Property(e => e.Q5outerCalc).HasColumnName("Q5OuterCalc");
            entity.Property(e => e.Time).HasMaxLength(20);
            entity.Property(e => e.Volume).HasMaxLength(20);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<VUnitcalc> entity);
    }
}
