// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Spv.WinForms.Models;

public partial class Auftragsstati
{
    public int Auftragsstatusid { get; set; }

    public string? Auftragsstatus { get; set; }
}