// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Spv.WinForms.Models;

public partial class Engineeringhn248konz
{
    public Guid EngineeringId { get; set; }

    public string? Drawing { get; set; }

    public string? Valvetype { get; set; }

    public double? UpperTolerance { get; set; }

    public double? LowerTolerance { get; set; }

    public double? Innerrate { get; set; }

    public double? Outerrate { get; set; }

    public double? Testpressure { get; set; }

    public double? Innertime { get; set; }

    public double? Outertime { get; set; }

    public string? Remarks { get; set; }

    public int? Deleted { get; set; }
}