// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Spv.WinForms.Models;

public partial class Group
{
    public int Groupid { get; set; }

    public string? Ngroup { get; set; }

    public string? Description { get; set; }
}