// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Spv.WinForms.Models;

public partial class Hn248konz
{
    public string? Zeichnung { get; set; }

    public string? Ventiltype { get; set; }

    public double? Innenrate { get; set; }

    public double? Aussenrate { get; set; }

    public double? Beipruefdruck { get; set; }

    public string? Innenzeit { get; set; }

    public string? Aussenzeit { get; set; }

    public string? Bemerkungen { get; set; }

    public string? ModifiedBy { get; set; }
}