// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Spv.WinForms.Models;

public partial class Hn248
{
    public string? ValveType { get; set; }

    public string? Pressure { get; set; }

    public double? Vessel { get; set; }

    public double? Time { get; set; }

    public double? Rate { get; set; }

    public string? Bemerkungen { get; set; }

    public string? ModifiedBy { get; set; }
}