namespace Spv.WinForms.Models;

public partial interface ISpvContextProcedures
{
    Task<int> BenchAddAsync(string pruefstand, string standort, int? zugeordnet, string pcname, int? baud, int? datenbits, int? stopbit, string parity, int? comnb, int? test, int? roundcnt, double? lowerp0, double? lowerp1, double? lowerp2, double? upperp0, double? upperp1, double? upperp2, double? nominalflow0, double? nominalflow1, double? nominalflow2, double? selftesttolerance, double? uptprelativ, double? lotprelativ, double? vesselfactor, double? ctrfactor, double? initdeltat, double? delayclosing, OutputParameter<int?> prid, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    Task<int> BenchUpdAsync(int? prid, string pruefstand, string standort, int? zugeordnet, string pcname, int? baud, int? datenbits, int? stopbit, string parity, int? comnb, int? test, int? roundcnt, double? lowerp0, double? lowerp1, double? lowerp2, double? upperp0, double? upperp1, double? upperp2, double? nominalflow0, double? nominalflow1, double? nominalflow2, double? selftesttolerance, double? uptprelativ, double? lotprelativ, double? vesselfactor, double? ctrfactor, double? initdeltat, double? delayclosing, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    Task<int> ChangePressureAsync(string fertnr, double? popen, double? pmax, double? pmin, int? userid, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    Task<int> ClosePruefungAsync(string fertnr, string srnr, int? auftragstypeid, int? prid, double? pdruck, int? userid, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    Task<int> DefaultSettingsUPDAsync(string Q5, string Q5inner, string Q5outer, string Pressure, string PressureP1, string PressureP2, string Volume, string Time, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    Task<int> GroupAddAsync(string ngroup, string description, OutputParameter<int?> groupid, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    Task<int> GroupAddRefAsync(int? userid, int? groupid, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    Task<int> GroupDelRefAsync(int? userid, int? groupid, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    Task<List<GrouprightGetResult>> GrouprightGetAsync(int? groupid, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    Task<int> GroupRightUpdAsync(int? groupid, int? modulid, int? access, int? @readonly, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    Task<int> GroupUpdAsync(int? groupid, string ngroup, string description, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    Task<int> LockSerialNbAsync(string fertnr, string srnr, int? auftragstypeid, int? prid, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    Task<int> MeassureUpdAsync(Guid? TestID, double? Value, int? IsInner, int? State, int? typ, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    Task<int> MeassureValInsAsync(Guid? TestID, double? MeassuredVal, double? MeassureTime, int? IsInner, Guid? ID, DateTime? MDate, int? ValveOk, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    Task<int> OrderAddAsync(string ordernb, int? ordertype, int? orderstateid, int? userid, OutputParameter<Guid?> orderid, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    Task<int> OrderDetailAddAsync(Guid? orderid, string matnb, string MatDesc, string valvetype, string drawing, double? p1, double? p2, double? innerrate, double? innertime, double? outerrate, double? outertime, int? userid, string serialnb, int? type, double? pressure, double? vessel, long? ID, double? ValueInner, double? ValueOuter, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    Task<int> PressureUpdAsync(string fertnr, int? auftragstypeid, int? deleted_von, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    Task<int> ReleaseAllLocksAsync(int? prid, int? auftragstypeid, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    Task<int> SelfTestAddAsync(DateTime? selftestdate, int? userid, OutputParameter<Guid?> id, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    Task<int> SelfTestAddDetailAsync(DateTime? selftestdate, int? userid, int? nozzlenb, double? debitvalue, double? flowvalue, int? valveok, OutputParameter<Guid?> id, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    Task<int> SendEMSUpdAsync(Guid? TestID, int? UserID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    Task<int> SettingsUpdAsync(int? id, string sapimportpath, string sapexportpath, string importmaster, string importdetail, string exportmaster, string exportdetail, string importoldpath, string charstandard, string charsonder, string charstorno, string sapprotokollpath, string sapclosedpath, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    Task<int> SystemsSettingsUPDAsync(string WebServiceLink, int? HasWebService, int? IsStandalone, int? HasSAPInterface, string SWUpdateLink, string EngImportPath, int? AutomaticMeassure, int? WaitForUserResponse, int? SelfTest, int? RelPressureTimeout, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    Task<int> UnLockSerialNbAsync(string fertnr, string srnr, int? auftragstypeid, int? prid, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    Task<int> UpdateHN248Async(string valvetype, double? p1, double? p2, double? vessel, double? time, double? rate, string remarks, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    Task<int> UpdateHN248KonzAsync(string drawingnb, string valvetype, double? p1, double? p2, double? innerrate, double? outerrate, double? pressure, double? innertime, double? outertime, string remarks, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    Task<int> UserAddAsync(string vorname, string nachname, string login, string passwort, string personalnr, int? gesperrt, int? groupid, OutputParameter<int?> userid, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    Task<int> UserSettingsUpdAsync(string keystr, string keyvalue, int? mitarbeiter, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    Task<int> UserUpdAsync(int? userid, string vorname, string nachname, string login, string passwort, string personalnr, int? gesperrt, int? groupid, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
}
