// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Spv.WinForms.Models;

public partial class MeassuredVal
{
    public Guid? TestId { get; set; }

    public DateTime? MeassureDate { get; set; }

    public double? Mtime { get; set; }

    public double? Mvalue { get; set; }

    public int? IsInner { get; set; }

    public Guid? Id { get; set; }

    public DateTime? Mdate { get; set; }

    public int? ValveOk { get; set; }
}