// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Spv.WinForms.Models;

public partial class PruefauftraegeStati
{
    public Guid? Pruefauftragid { get; set; }

    public int? Pruefstatusid { get; set; }

    public DateTime? Datum { get; set; }

    public int? Userid { get; set; }

    public int? Deleted { get; set; }

    public DateTime? DeletedAm { get; set; }

    public int? DeletedVon { get; set; }
}