// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Spv.WinForms.Models;

public partial class Pruefauftraege
{
    public Guid Pruefauftragid { get; set; }

    public string? Fertnr { get; set; }

    public string? Srnr { get; set; }

    public double? Pmax { get; set; }

    public double? Pmin { get; set; }

    public double? Popen { get; set; }

    public double? Pdruck { get; set; }

    public int? Prid { get; set; }

    public int? Pruefstatusid { get; set; }

    public int? Auftragstypeid { get; set; }

    public int? Userid { get; set; }

    public DateTime? DatumAm { get; set; }

    public int? Exportiert { get; set; }

    public DateTime? ExportiertAm { get; set; }

    public string? Abnahmeges { get; set; }

    public string? Abnahmenummer { get; set; }

    public int? Deleted { get; set; }

    public DateTime? DeletedAm { get; set; }

    public int? DeletedVon { get; set; }
}