// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Spv.WinForms.Models;

public partial class SelftestDetail
{
    public Guid? Id { get; set; }

    public DateTime? SelfTestDate { get; set; }

    public int? NozzleNb { get; set; }

    public double? DebitValue { get; set; }

    public double? FlowValue { get; set; }

    public int? ValveOk { get; set; }

    public DateTime? Created { get; set; }

    public int? CreatedBy { get; set; }
}