// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Spv.WinForms.Models;

public partial class SystemSetting
{
    public string? SysWebserviceLink { get; set; }

    public int? SysHasWebService { get; set; }

    public int? SysIsStandalone { get; set; }

    public int? SysHasSapinterface { get; set; }

    public string? SysSwupdateLink { get; set; }

    public string? SysEngImportPath { get; set; }

    public int? SysAutomaticMeassure { get; set; }

    public int? SysWaitForUserResponse { get; set; }

    public int? SysSelfTest { get; set; }

    public int? SysRelPressureTimeout { get; set; }
}