// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Spv.WinForms.Models;

public partial class Unit
{
    public string? UnitId { get; set; }

    public int? TypId { get; set; }

    public double? Faktor { get; set; }
}