// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Spv.WinForms.Models;

public partial class VMeassure
{
    public Guid? SerialId { get; set; }

    public Guid? TestId { get; set; }

    public int? State { get; set; }

    public double? P1 { get; set; }

    public double? P2 { get; set; }

    public double? Innerrate { get; set; }

    public double? Innertime { get; set; }

    public double? Outerrate { get; set; }

    public double? Outertime { get; set; }

    public double? Pressure { get; set; }

    public double? Vessel { get; set; }

    public double? ValueInner { get; set; }

    public double? ValueOuter { get; set; }

    public int? Issend2esm { get; set; }

    public double? Q5calc { get; set; }

    public double? Q5innerCalc { get; set; }

    public double? Q5outerCalc { get; set; }

    public double? PressureCalc { get; set; }

    public double? P1calc { get; set; }

    public double? P2calc { get; set; }

    public double? VolumeCalc { get; set; }

    public double? TimeCalc { get; set; }

    public int? Testtype { get; set; }

    public string? Q5 { get; set; }

    public string? Q5inner { get; set; }

    public string? Q5outer { get; set; }

    public string? PressureUnit { get; set; }

    public string? PressureP1 { get; set; }

    public string? PressureP2 { get; set; }

    public string? Volume { get; set; }

    public string? Time { get; set; }

    public string? TimeUnit { get; set; }
}