// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Spv.WinForms.Models;

public partial class VMeassuredVal
{
    public Guid? TestId { get; set; }

    public DateTime? MeassureDate { get; set; }

    public double? Mtime { get; set; }

    public double? MeassuredValue { get; set; }

    public string? MeassuredUnit { get; set; }

    public int? IsInner { get; set; }

    public Guid? Id { get; set; }

    public DateTime? Mdate { get; set; }

    public Guid? SerialId { get; set; }

    public double? P1 { get; set; }

    public double? P2 { get; set; }

    public double? DebitValue { get; set; }

    public int? State { get; set; }

    public int? TestType { get; set; }

    public Guid Orderid { get; set; }

    public string? Serialnb { get; set; }

    public string? ValveType { get; set; }

    public string? Drawing { get; set; }

    public int? Type { get; set; }

    public string? MatNb { get; set; }

    public string? MatDesc { get; set; }

    public long? Esmid { get; set; }

    public string? Q5 { get; set; }

    public double? Q5calc { get; set; }

    public string? Time { get; set; }

    public double? TimeCalc { get; set; }

    public int? ValveOk { get; set; }
}