// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Spv.WinForms.Models;

public partial class Columnheader
{
    public string Fieldname { get; set; } = null!;

    public string? Displayname { get; set; }

    public string Lang { get; set; } = null!;
}