// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Spv.WinForms.Models;

public partial class DefaultSetting
{
    public string? Q5 { get; set; }

    public string? Q5inner { get; set; }

    public string? Q5outer { get; set; }

    public string? Pressure { get; set; }

    public string? PressureP1 { get; set; }

    public string? PressureP2 { get; set; }

    public string? Volume { get; set; }

    public string? Time { get; set; }

    public DateTime? Created { get; set; }

    public Guid? CreatedBy { get; set; }

    public DateTime? LastEdit { get; set; }

    public Guid? LastEditBy { get; set; }

    public int? Status { get; set; }
}