// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Spv.WinForms.Models;

public partial class File
{
    public string Filename { get; set; } = null!;

    public int? Filesize { get; set; }

    public DateTime? Filedate { get; set; }

    public string? Filepath { get; set; }

    public int? Userid { get; set; }

    public DateTime? Datum { get; set; }

    public int? Queueindex { get; set; }
}