// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Spv.WinForms.Models;

public partial class Meassure
{
    public Guid? TestId { get; set; }

    public Guid? SerialId { get; set; }

    public double? P1 { get; set; }

    public double? P2 { get; set; }

    public double? Innerrate { get; set; }

    public double? Innertime { get; set; }

    public double? Outerrate { get; set; }

    public double? Outertime { get; set; }

    public double? Pressure { get; set; }

    public double? Vessel { get; set; }

    public double? ValueInner { get; set; }

    public DateTime? DateInner { get; set; }

    public double? ValueOuter { get; set; }

    public DateTime? DateOuter { get; set; }

    public int? State { get; set; }

    public DateTime? Send2esm { get; set; }

    public int? Send2esmBy { get; set; }

    public int? Issend2esm { get; set; }

    public int? TestType { get; set; }

    public DateTime? Created { get; set; }

    public int? CreatedBy { get; set; }

    public int? Isdeleted { get; set; }

    public DateTime? Deleted { get; set; }

    public int? DeletedBy { get; set; }
}