// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Spv.WinForms.Models;

public partial class OrdersDetail
{
    public Guid Orderid { get; set; }

    public Guid Serialid { get; set; }

    public string? Serialnb { get; set; }

    public string? ValveType { get; set; }

    public string? Drawing { get; set; }

    public int? Type { get; set; }

    public string? MatNb { get; set; }

    public string? MatDesc { get; set; }

    public long? Id { get; set; }

    public DateTime? Created { get; set; }

    public int? CreatedBy { get; set; }

    public int? Isdeleted { get; set; }

    public DateTime? Deleted { get; set; }

    public int? DeletedBy { get; set; }
}