// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Spv.WinForms.Models;

public partial class PruefLock
{
    public int? Prid { get; set; }

    public string? Fertnr { get; set; }

    public string? Srnr { get; set; }

    public int? Auftragstypeid { get; set; }

    public DateTime? Datum { get; set; }
}