// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Spv.WinForms.Models;

public partial class Selftest
{
    public Guid Id { get; set; }

    public DateTime? SelfTestDate { get; set; }

    public DateTime? Created { get; set; }

    public int? CreatedBy { get; set; }
}