// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Spv.WinForms.Models;

public partial class Setting
{
    public int Id { get; set; }

    public string? Sapimportpath { get; set; }

    public string? Sapexportpath { get; set; }

    public string? Importmaster { get; set; }

    public string? Importdetail { get; set; }

    public string? Exportmaster { get; set; }

    public string? Exportdetail { get; set; }

    public string? Sapimportoldpath { get; set; }

    public string? Charstandard { get; set; }

    public string? Charsonder { get; set; }

    public string? Charstorno { get; set; }

    public string? Sapprotokollpath { get; set; }

    public string? Sapclosedpath { get; set; }
}