// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Spv.WinForms.Models;

public partial class Testtypen
{
    public int Prueftypid { get; set; }

    public string? Prueftyp { get; set; }
}