// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Spv.WinForms.Models;

public partial class UserGroup
{
    public int? Groupid { get; set; }

    public int? Userid { get; set; }
}