// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Spv.WinForms.Models;

public partial class UserSetting
{
    public int? Userid { get; set; }

    public string? Keystr { get; set; }

    public string? Keyvalue { get; set; }
}